///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String vocoLogoBeyaz = 'assets/logoBeyazDuz.png';
  static const String vocoLogoYazi = 'assets/logoBeyazVoco.png';
  static const String backgroundImage = 'assets/backgroundImage.jpg';
  static const String bisiklet = 'assets/bisiklet.jpg';
  static const String dans = 'assets/dans.jpg';
  static const String parti = 'assets/parti.jpg';
  static const String trekking = 'assets/trekking.jpg';
  static const String yuruyus = 'assets/yuruyus.jpg';
  static const String iphone12 = 'assets/iphone12.png';



  

}
